const actionTypes = {
    GET_ALL_DETAILS: 'GET_ALL_DETAILS',
    UPDATE_ALL_DETAILS: 'UPDATE_ALL_DETAILS',

    REQUEST_UPDATE_BASIC_DETAILS: 'REQUEST_UPDATE_BASIC_DETAILS',
    UPDATE_BASIC_DETAILS: 'UPDATE_BASIC_DETAILS',

    STICKY_NOTE_MODIFICATION: 'STICKY_NOTE_MODIFICATION',
    UPDATE_STICKY_NOTES: 'UPDATE_STICKY_NOTES',

    ADD_TASK_ITEM: 'ADD_TASK_ITEM',
    UPDATE_TASK_ITEM: 'UPDATE_TASK_ITEM',
    DELETE_TASK_ITEM: 'DELETE_TASK_ITEM',
    HANDLE_ERROR: 'HANDLE_ERROR'
};

export default actionTypes;
