const actionTypes = {
    GET_ALL_DETAILS: 'GET_ALL_DETAILS',
    UPDATE_ALL_DETAILS: 'UPDATE_ALL_DETAILS',

    REQUEST_UPDATE_BASIC_DETAILS: 'REQUEST_UPDATE_BASIC_DETAILS',
    UPDATE_BASIC_DETAILS: 'UPDATE_BASIC_DETAILS',

    STICKY_NOTE_MODIFICATION: 'STICKY_NOTE_MODIFICATION',
    UPDATE_STICKY_NOTES: 'UPDATE_STICKY_NOTES',

    TASKS_MODIFICATION: 'TASKS_MODIFICATION',
    UPDATE_TASKS: 'UPDATE_TASKS',

    RENDER_PORTAL: 'RENDER_PORTAL',
    CLOSE_PORTAL: 'CLOSE_PORTAL',
    ERROR_OCCURRED: 'ERROR_OCCURRED'
};

export default actionTypes;
